# Generated by Django 4.2.4 on 2023-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images/"
            ),
        ),
    ]
