# Generated by Django 4.2.4 on 2023-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("AL", "aluno"), ("PR", "professor")],
                default="AL",
                max_length=2,
            ),
        ),
    ]
