# Generated by Django 4.2.4 on 2023-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("usuario", "0002_usuario_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="foto",
        ),
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="uploader.image"
            ),
        ),
    ]
