# Generated by Django 4.2.4 on 2023-08-15 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fabrica", "0006_post_rename_texto_projeto_descricao_and_more"),
        ("usuario", "0002_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="tipo_usuario",
        ),
        migrations.DeleteModel(
            name="TipoUsuario",
        ),
    ]
