# Generated by Django 4.2.5 on 2023-11-21 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0003_remove_usuario_foto_usuario_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="foto",
        ),
    ]
