# Generated by Django 4.2.4 on 2023-08-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fabrica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tarefas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tarefas_alunos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="alunos",
            field=models.ManyToManyField(
                related_name="alunos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="projeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="fabrica.projeto",
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to="fabrica.post",
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
