# Generated by Django 4.2.4 on 2023-08-11 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0002_usuario_tipo_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fabrica", "0002_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembrosProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projeto_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projeto_id",
                        to="fabrica.projeto",
                    ),
                ),
                (
                    "tipo_usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipo_usuario_id",
                        to="usuario.tipousuario",
                    ),
                ),
                (
                    "usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membros_projeto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
