# Generated by Django 4.2.4 on 2023-08-11 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fabrica", "0003_membrosprojeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="membros",
            field=models.ManyToManyField(
                related_name="membros", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
