# Generated by Django 4.2.4 on 2023-08-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fabrica", "0005_usuariostipo_delete_membrosprojeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.CharField(max_length=2500)),
            ],
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="texto",
            new_name="descricao",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="membros",
        ),
        migrations.AddField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="UsuariosTipo",
        ),
        migrations.AddField(
            model_name="post",
            name="projeto_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="fabrica.projeto",
            ),
        ),
    ]
