# Generated by Django 4.2.4 on 2023-08-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fabrica", "0006_post_rename_texto_projeto_descricao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="usuario",
            new_name="usuario_id",
        ),
        migrations.AddField(
            model_name="comentario",
            name="post_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comentarios",
                to="fabrica.post",
            ),
            preserve_default=False,
        ),
    ]
