# Generated by Django 4.2.4 on 2023-08-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fabrica", "0007_rename_usuario_comentario_usuario_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="grupo_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
